// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LS2GS.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LS2GS {

  /// <summary>Holder for reflection information generated from LS2GS.proto</summary>
  public static partial class LS2GSReflection {

    #region Descriptor
    /// <summary>File descriptor for LS2GS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LS2GSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtMUzJHUy5wcm90bxIFTFMyR1MaEFJlc3VsdENvZGUucHJvdG8iTgoXcmVx",
            "VmVyaWZpY2F0aW9uQXNrTG9naW4SDwoHYWNjb3VudBgBIAEoCRIQCghwYXNz",
            "d29yZBgCIAEoCRIQCghjbGllbnRJZBgDIAEoBSKpAQoYcmVzcFZlcmlmaWNh",
            "dGlvbkFza0xvZ2luEhgKA2VychgBIAEoDjILLlJlc3VsdENvZGUSEQoJaXNT",
            "dWNjZXNzGAIgASgIEhQKDGdhdGVTZXJ2ZXJJcBgDIAEoCRIWCg5nYXRlU2Vy",
            "dmVyUG9ydBgEIAEoBRIOCgZ1c2VySWQYBSABKAkSEwoLdXNlckFjY291bnQY",
            "BiABKAkSDQoFdG9rZW4YByABKAkqSQoFTXNnSWQSCQoFRmlyc3QQABIKCgVC",
            "ZWdpbhDgXRIfChpMUzJHU19WZXJpZmljYXRpb25Bc2tMb2dpbhDhXRIICgNF",
            "bmQQxF5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ResultCodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LS2GS.MsgId), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LS2GS.reqVerificationAskLogin), global::LS2GS.reqVerificationAskLogin.Parser, new[]{ "Account", "Password", "ClientId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LS2GS.respVerificationAskLogin), global::LS2GS.respVerificationAskLogin.Parser, new[]{ "Err", "IsSuccess", "GateServerIp", "GateServerPort", "UserId", "UserAccount", "Token" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("First")] First = 0,
    [pbr::OriginalName("Begin")] Begin = 12000,
    [pbr::OriginalName("LS2GS_VerificationAskLogin")] Ls2GsVerificationAskLogin = 12001,
    [pbr::OriginalName("End")] End = 12100,
  }

  #endregion

  #region Messages
  public sealed partial class reqVerificationAskLogin : pb::IMessage<reqVerificationAskLogin> {
    private static readonly pb::MessageParser<reqVerificationAskLogin> _parser = new pb::MessageParser<reqVerificationAskLogin>(() => new reqVerificationAskLogin());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<reqVerificationAskLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LS2GS.LS2GSReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public reqVerificationAskLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public reqVerificationAskLogin(reqVerificationAskLogin other) : this() {
      account_ = other.account_;
      password_ = other.password_;
      clientId_ = other.clientId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public reqVerificationAskLogin Clone() {
      return new reqVerificationAskLogin(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 3;
    private int clientId_;
    /// <summary>
    /// 在 LS 上自动创建的 clientId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientId {
      get { return clientId_; }
      set {
        clientId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as reqVerificationAskLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(reqVerificationAskLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if (Password != other.Password) return false;
      if (ClientId != other.ClientId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (ClientId != 0) hash ^= ClientId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (ClientId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ClientId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (ClientId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(reqVerificationAskLogin other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.ClientId != 0) {
        ClientId = other.ClientId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            ClientId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class respVerificationAskLogin : pb::IMessage<respVerificationAskLogin> {
    private static readonly pb::MessageParser<respVerificationAskLogin> _parser = new pb::MessageParser<respVerificationAskLogin>(() => new respVerificationAskLogin());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<respVerificationAskLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LS2GS.LS2GSReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public respVerificationAskLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public respVerificationAskLogin(respVerificationAskLogin other) : this() {
      err_ = other.err_;
      isSuccess_ = other.isSuccess_;
      gateServerIp_ = other.gateServerIp_;
      gateServerPort_ = other.gateServerPort_;
      userId_ = other.userId_;
      userAccount_ = other.userAccount_;
      token_ = other.token_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public respVerificationAskLogin Clone() {
      return new respVerificationAskLogin(this);
    }

    /// <summary>Field number for the "err" field.</summary>
    public const int ErrFieldNumber = 1;
    private global::ResultCode err_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ResultCode Err {
      get { return err_; }
      set {
        err_ = value;
      }
    }

    /// <summary>Field number for the "isSuccess" field.</summary>
    public const int IsSuccessFieldNumber = 2;
    private bool isSuccess_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSuccess {
      get { return isSuccess_; }
      set {
        isSuccess_ = value;
      }
    }

    /// <summary>Field number for the "gateServerIp" field.</summary>
    public const int GateServerIpFieldNumber = 3;
    private string gateServerIp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GateServerIp {
      get { return gateServerIp_; }
      set {
        gateServerIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gateServerPort" field.</summary>
    public const int GateServerPortFieldNumber = 4;
    private int gateServerPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GateServerPort {
      get { return gateServerPort_; }
      set {
        gateServerPort_ = value;
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 5;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userAccount" field.</summary>
    public const int UserAccountFieldNumber = 6;
    private string userAccount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserAccount {
      get { return userAccount_; }
      set {
        userAccount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 7;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as respVerificationAskLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(respVerificationAskLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Err != other.Err) return false;
      if (IsSuccess != other.IsSuccess) return false;
      if (GateServerIp != other.GateServerIp) return false;
      if (GateServerPort != other.GateServerPort) return false;
      if (UserId != other.UserId) return false;
      if (UserAccount != other.UserAccount) return false;
      if (Token != other.Token) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Err != 0) hash ^= Err.GetHashCode();
      if (IsSuccess != false) hash ^= IsSuccess.GetHashCode();
      if (GateServerIp.Length != 0) hash ^= GateServerIp.GetHashCode();
      if (GateServerPort != 0) hash ^= GateServerPort.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (UserAccount.Length != 0) hash ^= UserAccount.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Err != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Err);
      }
      if (IsSuccess != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsSuccess);
      }
      if (GateServerIp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GateServerIp);
      }
      if (GateServerPort != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GateServerPort);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UserId);
      }
      if (UserAccount.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(UserAccount);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Token);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Err != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Err);
      }
      if (IsSuccess != false) {
        size += 1 + 1;
      }
      if (GateServerIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GateServerIp);
      }
      if (GateServerPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GateServerPort);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (UserAccount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserAccount);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(respVerificationAskLogin other) {
      if (other == null) {
        return;
      }
      if (other.Err != 0) {
        Err = other.Err;
      }
      if (other.IsSuccess != false) {
        IsSuccess = other.IsSuccess;
      }
      if (other.GateServerIp.Length != 0) {
        GateServerIp = other.GateServerIp;
      }
      if (other.GateServerPort != 0) {
        GateServerPort = other.GateServerPort;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.UserAccount.Length != 0) {
        UserAccount = other.UserAccount;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            err_ = (global::ResultCode) input.ReadEnum();
            break;
          }
          case 16: {
            IsSuccess = input.ReadBool();
            break;
          }
          case 26: {
            GateServerIp = input.ReadString();
            break;
          }
          case 32: {
            GateServerPort = input.ReadInt32();
            break;
          }
          case 42: {
            UserId = input.ReadString();
            break;
          }
          case 50: {
            UserAccount = input.ReadString();
            break;
          }
          case 58: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
